# Generated by Django 3.0.5 on 2020-05-24 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='モデル名')),
                ('model_dev_date', models.DateField(default=django.utils.timezone.now)),
                ('train_start', models.DateField(verbose_name='訓練データ開始日')),
                ('train_end', models.DateField(verbose_name='訓練データ終了日')),
                ('test_start', models.DateField(verbose_name='テストデータ開始日')),
                ('test_end', models.DateField(verbose_name='テストデータ終了日')),
                ('epoch', models.IntegerField(verbose_name='エポック数')),
                ('batch_size', models.IntegerField(verbose_name='バッチサイズ')),
                ('train_acc', models.FloatField(default=0.0, verbose_name='訓練データ正答率')),
                ('test_acc', models.FloatField(default=0.0, verbose_name='テストデータ正答率')),
                ('images', models.ImageField(default='null.jpg', upload_to='', verbose_name='学習過程')),
            ],
        ),
    ]
