# Generated by Django 3.0.5 on 2020-06-03 13:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketforecastmodel',
            name='forecast_model',
            field=models.CharField(default=10, max_length=100, verbose_name='学習方法'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketforecastmodel',
            name='model_defined_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 3, 13, 31, 38, 116878, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='marketforecastmodel',
            name='title',
            field=models.CharField(default=20200101, max_length=100, verbose_name='モデル名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketforecastmodel',
            name='train_num',
            field=models.IntegerField(default=2, verbose_name='学習データ数'),
            preserve_default=False,
        ),
    ]
