# Generated by Django 3.0.5 on 2020-06-04 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forecast_app', '0002_auto_20200603_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketforecastmodel',
            name='weather',
            field=models.CharField(default='cloudy', max_length=100, verbose_name='予報'),
        ),
        migrations.AlterField(
            model_name='marketforecastmodel',
            name='forecast_model',
            field=models.CharField(default='binomial logit', max_length=100, verbose_name='アルゴリズム'),
        ),
        migrations.AlterField(
            model_name='marketforecastmodel',
            name='model_defined_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='最終更新日'),
        ),
        migrations.AlterField(
            model_name='marketforecastmodel',
            name='train_num',
            field=models.IntegerField(default=2600, verbose_name='学習データ数'),
        ),
    ]
