# Generated by Django 3.0.5 on 2020-07-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='登録ポートフォリオ')),
                ('weight_DB', models.FloatField(default=0.15, verbose_name='国内債券')),
                ('weight_DE', models.FloatField(default=0.15, verbose_name='国内株式')),
                ('weight_FB', models.FloatField(default=0.15, verbose_name='先進国債券')),
                ('weight_FE', models.FloatField(default=0.15, verbose_name='先進国株式')),
                ('weight_EB', models.FloatField(default=0.1, verbose_name='新興国債券')),
                ('weight_EE', models.FloatField(default=0.1, verbose_name='新興国株式')),
                ('weight_DR', models.FloatField(default=0.1, verbose_name='国内リート')),
                ('weight_FR', models.FloatField(default=0.1, verbose_name='先進国リート')),
            ],
        ),
    ]
