# Generated by Django 3.0.5 on 2020-06-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(default=1, max_length=200, verbose_name='link'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.CharField(max_length=200, verbose_name='content'),
        ),
    ]
